version: 2.1

orbs:
  android: circleci/android@0.2.1
  gradle: circleci/gradle@2.0.0

jobs:
  build:
    environment:
      JVM_OPTS: -Xmx3200m
    executor:
      name: android/android
      sdk-version: '27'
    steps:
    - checkout
    - run:
        name: Synchronize submodules
        command: git submodule sync
    - run:
        name: Update submodules
        command: git submodule update --init
    - run:
        name: Fix gradlew permissions
        command: sudo chmod +x ./gradlew
    - gradle/with_cache:
        steps:
        - android/restore-build-cache
        - run:
            name: Build Release
            command: ./gradlew assembleFlossRelease
        - android/save-build-cache
    - store_artifacts:
        path: app/build/outputs/apk/floss/release
        destination: apk
